name: build

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node_version }}'
          registry-url: 'https://registry.npmjs.org'

      # pulls all tags (needed for lerna to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308
      # - uses: actions/setup-node@v1

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn_cache

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn_cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Bootstrap
        run: yarn lerna bootstrap && yarn lerna link

      - name: Test
        run: yarn test

      - name: Generate static site
        run: yarn lerna run generate
