name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node_version }}"
          cache: 'npm'

      - name: Upgrade npm
        run: npm i -g npm

      # pulls all tags (needed for lerna to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: npx lerna bootstrap --hoist

      - name: Test
        run: npm --node-options='--experimental-vm-modules' run test

      - name: Generate static site
        run: npx lerna run generate
