name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node_version }}"
          registry-url: "https://registry.npmjs.org"

      # pulls all tags (needed for lerna to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: npx lerna bootstrap --hoist

      - name: Test
        run: npm test

      - name: "File generation check"
        uses: setare/git-changes-action@v0.1.4
        with:
          github_token: ${{ github.token }}

      - name: Generate static site
        run: npx lerna run generate
