name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18, 20]

    steps:
      - uses: actions/checkout@v4
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node_version }}"
          cache: npm

      - name: Upgrade npm
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
