name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node_version }}"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      # pulls all tags (needed for lerna to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: Upgrade npm
        run: npm i -g npm

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: npx lerna bootstrap --hoist

      - name: Test
        run: npm --node-options='--experimental-vm-modules' run test

      - name: Publish
        run: |
          npx lerna version -y --conventional-commits --create-release github
          npx lerna publish -y from-package
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Generate static site
        run: npx lerna run generate

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/reveal-compiler-explorer-demo/_static
