name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          persist-credentials: false
          
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npx semantic-release
